version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify the Node.js version to install
    commands:
      - echo "Node.js installed"

  pre_build:
    commands:
      - echo "It's a prebuild phase"

  build:
    commands:
      - echo "It's a build phase"

  post_build:
    commands:
      - echo "It's a post build phase"
      - grep -Fq "Dost" index.html

artifacts:
  files:
    - '**/*'
